### ISSUE TITLE
Possibility to have a systematic runtime exception class hierarchy added to the handled exceptions

### ISSUE THREAD

**Issue by silentFred** [coveo/feign-error-decoder#5]
Hi again :)

Managed to get it working. After stepping into the code I noticed that the exception translation will only work if the feign client declares that it throws a particular exception the inherits from the base exception.

We use runtime exceptions to make our code less verbose (and a bunch of other reasons as well). Is there a way to properly instantiate the decoder without specifying an exception thrown on the client interface?

Cheers for now and thanks again!

**Comment by jebeaudet** [comment]
Could you make your runtime exceptions all inherit from a base exception? You could then have your interface api like this : 
```
void createUser(String username, String password) throws YourBaseRuntimeException;
```
 Of course you'd need the classpath scanning that Spring has here, do you use Spring? Otherwise, you're stuck with specifying all the runtime exceptions thrown on your api of code your classpath scanning (it's not _that_ hard but it has not been coded since we're on Spring.

**Comment by silentFred** [comment]
We use Spring so we are golden. Was just wondering how to not have to
specify it on the interface. It's better to have it there to be honest :)

**Comment by jebeaudet** [comment]
Well actually, I think it's kind of error prone to have to specify runtime exceptions on your api (as you could just forget to add it and you wouldn't get the proper error handling) but in your case, as the code stands today, that's unfortunately your only choice.

This being said, I think that having an optional runtime exception (abstract or concrete) automatically added in the `exceptionsThrown` map would be a nice addition to the library. I'll try to look into it or if you want you can submit a PR feel free to!

**Comment by silentFred** [comment]
That would be a nifty addition! Will also look into it if I get some time :)

**Comment by jebeaudet** [comment]
I gave it a shot in https://github.com/coveo/feign-error-decoder/commit/6d49a4e1a11c8e040348e25edd7a736da3349589. I'm not entirely sure if it'll stay that way though, it's a bit rough around the edges. I'd like to provide a common way for checked and runtime exception to be added to the relevant map, including classpath scanning support along with additional validation for the unicity of keys. In the meantime, i've exposed the `ClassHierarchySupplier` to subclasses along with the other required parameters.

You now have a hook in `protected void addAdditionalRuntimeExceptions(Map<String, ThrownExceptionDetails<RuntimeException>> runtimeExceptionsThrown)` in your subclass to add custom `RuntimeException` to a distinct map. Have a look at https://github.com/coveo/feign-error-decoder/blob/master/src/test/java/com/coveo/feign/ServiceExceptionErrorDecoder.java for an example on how to use it, it's a simple case of a single exception though, no classpath scanning involved.

I've also deployed a 1.4.0-SNAPSHOT release to maven central so you can try it out. Let me know if it fits your use case and if you find any issues.

**Comment by jebeaudet** [comment]
We could have an implementation of `ResponseErrorHandler` in rest templates though it would only support runtime exceptions as far as I can see from the interface.

**Comment by silentFred** [comment]
Lucky for me we only use runtime exceptions =P

**Comment by jebeaudet** [comment]
Snapshot is available only on https://oss.sonatype.org/content/repositories/snapshots/ btw, not on central. You're free to build it yourself if it's easier for you.

**Comment by silentFred** [comment]
@jebeaudet I finally have some time to play with this again. What was introduced in 1.3.0? Seems I have some missing spring jdbc stuff now?

**Comment by jebeaudet** [comment]
On which version were you before upgrading? 1.2.0?
Do you have the error message you get? There should not be any jdbc dependency for this project so I'm not entirely sure the lib is related to your error.

**Comment by silentFred** [comment]
I went from 1.2.0 to 1.4.0-SNAPSHOT. 1.3.0 also gives the same error: java.lang.ClassNotFoundException: org.springframework.jdbc.core.ConnectionCallback

Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [jar:file:/C:/Users/someUser/.m2/repository/org/springframework/boot/spring-boot-test-autoconfigure/1.5.10.RELEASE/spring-boot-test-autoconfigure-1.5.10.RELEASE.jar!/org/springframework/boot/test/autoconfigure/jdbc/JdbcTest.class]; nested exception is java.lang.NoClassDefFoundError: org/springframework/jdbc/core/ConnectionCallback
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:311)
	at com.coveo.feign.hierarchy.CachedSpringClassHierarchySupplier.<init>(CachedSpringClassHierarchySupplier.java:25)
	at com.coveo.feign.ReflectionErrorDecoder.<init>(ReflectionErrorDecoder.java:71)
	at com.coveo.feign.ReflectionErrorDecoder.<init>(ReflectionErrorDecoder.java:58)
	at discovery.portal.das.exceptions.handling.advice.FeignErrorDecoder.<init>(FeignErrorDecoder.java:14)
	at discovery.portal.das.exceptions.handling.TestConfiguration.testClient(TestConfiguration.java:24)
	at discovery.portal.das.exceptions.handling.TestConfiguration$$EnhancerBySpringCGLIB$$9f077845.CGLIB$testClient$0(<generated>)
	at discovery.portal.das.exceptions.handling.TestConfiguration$$EnhancerBySpringCGLIB$$9f077845$$FastClassBySpringCGLIB$$42e586a6.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at discovery.portal.das.exceptions.handling.TestConfiguration$$EnhancerBySpringCGLIB$$9f077845.testClient(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 63 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/jdbc/core/ConnectionCallback
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at java.lang.Class.getEnumConstantsShared(Class.java:3311)
	at java.lang.Class.enumConstantDirectory(Class.java:3341)
	at java.lang.Enum.valueOf(Enum.java:232)
	at sun.reflect.annotation.AnnotationParser.parseEnumValue(AnnotationParser.java:483)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:347)
	at java.lang.reflect.Method.getDefaultValue(Method.java:606)
	at org.springframework.core.annotation.AnnotationUtils.registerDefaultValues(AnnotationUtils.java:1178)
	at org.springframework.core.type.classreading.RecursiveAnnotationAttributesVisitor.visitEnd(RecursiveAnnotationAttributesVisitor.java:42)
	at org.springframework.core.type.classreading.AnnotationAttributesReadingVisitor.visitEnd(AnnotationAttributesReadingVisitor.java:64)
	at org.springframework.asm.ClassReader.readAnnotationValues(ClassReader.java:2020)
	at org.springframework.asm.ClassReader.accept(ClassReader.java:676)
	at org.springframework.asm.ClassReader.accept(ClassReader.java:527)
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:64)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:102)
	at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:102)
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:287)
	... 78 more
Caused by: java.lang.ClassNotFoundException: org.springframework.jdbc.core.ConnectionCallback
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

It also seems when the caching was introduced, spring startup time was increased dramatically. I'm stumped...

**Comment by jebeaudet** [comment]
Yea the caching was a very low hanging fruit, I highly suggest you upgrade just for that. We saw major improvements on our end too.

As for your problem, I see you're using the constructor without specifying the `basePackage`, did you change that? Try specifying it in the constructor (you could use `discovery.portal` from what I can read from your stacktrace).

Also, what do you use as a type `S extends Exception` in `discovery.portal.das.exceptions.handling.advice.FeignErrorDecoder`?

**Comment by silentFred** [comment]
Sorry, my comment might be a bit unclear -> i meant to say that the cashing has negatively impacted application startup. Taking much longer now.

I'm not too sure I understand the interface. Do you mean I should be passing in the string of the base package the exceptions are in (as with Spring's component scan annotation/config)?

Here is my setup so far:

`
public class FeignErrorDecoder extends ReflectionErrorDecoder<ErrorResponse, AbstractClientException> {

    public FeignErrorDecoder(Class<?> apiClass) {
        super(apiClass, ErrorResponse.class, AbstractClientException.class);
    }

    @Override
    protected String getKeyFromException(AbstractClientException exception) {
        return exception.getExceptionCode();
    }

    @Override
    protected String getKeyFromResponse(ErrorResponse errorResponse) {
        return errorResponse.getExceptionCode();
    }

    @Override
    protected String getMessageFromResponse(ErrorResponse errorResponse) {
        return errorResponse.getMessage();
    }

    @Override
    protected void addAdditionalRuntimeExceptions(Map<String, ThrownExceptionDetails<RuntimeException>> runtimeExceptionsThrown) {
        ThrownExceptionDetails<RuntimeException> clientException = new ThrownExceptionDetails<>();
        clientException.setClazz(AbstractClientException.class);
        clientException.setExceptionSupplier(() -> new ClientException(""));
        runtimeExceptionsThrown.put("0000", clientException);
        super.addAdditionalRuntimeExceptions(runtimeExceptionsThrown);

    }
}
`

**Comment by silentFred** [comment]
@jebeaudet I just saw the overloaded constructor that has the base package parameter. Passing that in with something sensible link the root of the package where my exception classes are solved the odd jdbc issue. I guess without a base package the lib just scans the entire classpath and ends up hitting some issues with spring classes it assumes is there? - Thank you for entertaining my questions. Learning quite a bit here!

**Comment by silentFred** [comment]
Hi there,

I'm developing a library component so all usage is via test at the moment. The performance issue I was experiencing was due to the missing package name in the decoder constructor.

Sorry for messing up this thread with unrelated stuff, but do you perhaps have an example of how to use the fallback decoder? There are some cases where clients won't response with known error payloads and I'd like to capture those properly and throw a base level exception

**Comment by jebeaudet** [comment]
Did you get a chance to run with the new log levels? Sorry I didn't get back to you sooner!

**Comment by silentFred** [comment]
Hi. Never got to trying the different log levels but I solved the problem by specifying the missing package name so all smiles here!

**Comment by jebeaudet** [comment]
Excellent news, glad you could make it work!

I'll close this issue for now, feel free to reopen if you think I missed something. 

I'll work on final 1.4 soon, in the meantime I encourage you to use the latest snapshot as I've bumped a bunch of dependencies, notably jackson-databind that had a CVE in it.
